<a href="https://colab.research.google.com/github/suruanush/Pandas/blob/main/Pandas_Dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. DataFrames

In [ ]:
employee1 = pd.Series({'Name' : 'Utkarsh', 'ID' : 1, 'Gender' : 'Male', 'Salary':95000})
employee2 = pd.Series({'Name' : 'Kartik', 'ID' : 2, 'Gender' : 'Male','Salary':85000})
employee3 = pd.Series({'Name' : 'Aishwarya', 'ID' : 3, 'Gender' : 'Female','Salary':75000})
employee4 = pd.Series({'Name' : 'Anand', 'ID' : 4, 'Gender' : 'Male','Salary':65000})
employee5 = pd.Series({'Name' : 'Shalini', 'ID' : 5, 'Gender' : 'Female','Salary':90000})
employee6 = pd.Series({'Name' : 'Pratik', 'ID' : 6, 'Gender' : 'Male','Salary':80000})
employee7 = pd.Series({'Name' : 'Monalika', 'ID' : 7, 'Gender' : 'Female','Salary':70000})
employee8 = pd.Series({'Name' : 'Ayesha', 'ID' : 8, 'Gender' : 'Female','Salary':60000})
employee9 = pd.Series({'Name' : 'Anant', 'ID' : 9, 'Gender' : 'Male','Salary':100000})
employee10 = pd.Series({'Name' : 'Shamiksha', 'ID' : 10, 'Gender' : 'Female','Salary':45000})
employee11 = pd.Series({'Name' : 'Prashant', 'ID' : 11, 'Gender' : 'Male','Salary':55000})
employee12 = pd.Series({'Name' : 'Mohini', 'ID' : 12, 'Gender' : 'Female','Salary':65000})

In [ ]:
employee3

Name      Aishwarya
ID                3
Gender       Female
Salary        75000
dtype: object

In [ ]:
employees = [employee1,employee2,employee3,employee4,employee5,employee6,employee7,employee8,employee9,employee10,employee11,employee12]
df1 = pd.DataFrame(data = employees, index = range(101,113))
df1

          Name  ID  Gender  Salary
101    Utkarsh   1    Male   95000
102     Kartik   2    Male   85000
103  Aishwarya   3  Female   75000
104      Anand   4    Male   65000
105    Shalini   5  Female   90000
106     Pratik   6    Male   80000
107   Monalika   7  Female   70000
108     Ayesha   8  Female   60000
109      Anant   9    Male  100000
110  Shamiksha  10  Female   45000
111   Prashant  11    Male   55000
112     Mohini  12  Female   65000

 - Single and two dimensional data
 - Rows and columns format
 - Tabular data
 - Data Frame
 - Structured data
 - Unstructured data

In [ ]:
type(df1)

pandas.core.frame.DataFrame

In [ ]:
df1.head(3)

          Name  ID  Gender  Salary
101    Utkarsh   1    Male   95000
102     Kartik   2    Male   85000
103  Aishwarya   3  Female   75000

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 101 to 112
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    12 non-null     object
 1   ID      12 non-null     int64
 2   Gender  12 non-null     object
 3   Salary  12 non-null     int64
dtypes: int64(2), object(2)
memory usage: 516.0+ bytes

In [ ]:
list(df1.index)

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112]

In [ ]:
df1.values

array([['Utkarsh', 1, 'Male', 95000],
       ['Kartik', 2, 'Male', 85000],
       ['Aishwarya', 3, 'Female', 75000],
       ['Anand', 4, 'Male', 65000],
       ['Shalini', 5, 'Female', 90000],
       ['Pratik', 6, 'Male', 80000],
       ['Monalika', 7, 'Female', 70000],
       ['Ayesha', 8, 'Female', 60000],
       ['Anant', 9, 'Male', 100000],
       ['Shamiksha', 10, 'Female', 45000],
       ['Prashant', 11, 'Male', 55000],
       ['Mohini', 12, 'Female', 65000]], dtype=object)

In [ ]:
df1.columns

Index(['Name', 'ID', 'Gender', 'Salary'], dtype='object')

In [ ]:
df1.name = 'Employee_Details'
df1.index.name = 'Employee_ID'

In [ ]:
df1.name

'Employee_Details'

In [ ]:
df1.index.name

'Employee_ID'

In [ ]:
df1.describe()

              ID         Salary
count  12.000000      12.000000
mean    6.500000   73750.000000
std     3.605551   16804.355496
min     1.000000   45000.000000
25%     3.750000   63750.000000
50%     6.500000   72500.000000
75%     9.250000   86250.000000
max    12.000000  100000.000000

## Accessing data from DataFrame

In [ ]:
df1

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5  Female   90000
106             Pratik   6    Male   80000
107           Monalika   7  Female   70000
108             Ayesha   8  Female   60000
109              Anant   9    Male  100000
110          Shamiksha  10  Female   45000
111           Prashant  11    Male   55000
112             Mohini  12  Female   65000

#### Accessing Columns

In [ ]:
df1['Name']

Employee_ID
101      Utkarsh
102       Kartik
103    Aishwarya
104        Anand
105      Shalini
106       Pratik
107     Monalika
108       Ayesha
109        Anant
110    Shamiksha
111     Prashant
112       Mohini
Name: Name, dtype: object

In [ ]:
df1['Salary']

Employee_ID
101     95000
102     85000
103     75000
104     65000
105     90000
106     80000
107     70000
108     60000
109    100000
110     45000
111     55000
112     65000
Name: Salary, dtype: int64

In [ ]:
df1[['Name', 'Salary']]

                  Name  Salary
Employee_ID
101            Utkarsh   95000
102             Kartik   85000
103          Aishwarya   75000
104              Anand   65000
105            Shalini   90000
106             Pratik   80000
107           Monalika   70000
108             Ayesha   60000
109              Anant  100000
110          Shamiksha   45000
111           Prashant   55000
112             Mohini   65000

In [ ]:
df1.Name        # Columns of a dataframe are also its attributes

Employee_ID
101      Utkarsh
102       Kartik
103    Aishwarya
104        Anand
105      Shalini
106       Pratik
107     Monalika
108       Ayesha
109        Anant
110    Shamiksha
111     Prashant
112       Mohini
Name: Name, dtype: object

In [ ]:
df1.Salary

Employee_ID
101     95000
102     85000
103     75000
104     65000
105     90000
106     80000
107     70000
108     60000
109    100000
110     45000
111     55000
112     65000
Name: Salary, dtype: int64

#### Accessing Records (Rows)

In [ ]:
df1.loc[101]      # Provided index

Name      Utkarsh
ID              1
Gender       Male
Salary      95000
Name: 101, dtype: object

In [ ]:
df1.iloc[0]        # Default indexing

Name      Utkarsh
ID              1
Gender       Male
Salary      95000
Name: 101, dtype: object

In [ ]:
df1.loc[105]

Name      Shalini
ID              5
Gender     Female
Salary      90000
Name: 105, dtype: object

In [ ]:
df1.loc[[101,105,109]]

                Name  ID  Gender  Salary
Employee_ID
101          Utkarsh   1    Male   95000
105          Shalini   5  Female   90000
109            Anant   9    Male  100000

In [ ]:
df1.iloc[[0,4,6,9]]

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
105            Shalini   5  Female   90000
107           Monalika   7  Female   70000
110          Shamiksha  10  Female   45000

### Accessing Specific Values

In [ ]:
df1

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5  Female   90000
106             Pratik   6    Male   80000
107           Monalika   7  Female   70000
108             Ayesha   8  Female   60000
109              Anant   9    Male  100000
110          Shamiksha  10  Female   45000
111           Prashant  11    Male   55000
112             Mohini  12  Female   65000

In [ ]:
df1.loc[105]['Salary']

90000

In [ ]:
df1.loc[103]['Name']

'Aishwarya'

In [ ]:
df1.iloc[3]['Salary']

65000

In [ ]:
df1.iloc[2]['Name']

'Aishwarya'

In [ ]:
df1.Salary[105]

90000

In [ ]:
df1.Name[103]

'Aishwarya'

In [ ]:
df1.loc[[101,105,108]]['Salary']

Employee_ID
101    95000
105    90000
108    60000
Name: Salary, dtype: int64

In [ ]:
df1.loc[[101,105,108]][['Name', 'Salary']]

                Name  Salary
Employee_ID
101          Utkarsh   95000
105          Shalini   90000
108           Ayesha   60000

In [ ]:
df1.iloc[[0,4,7,9]][['Name', 'Salary']]

                  Name  Salary
Employee_ID
101            Utkarsh   95000
105            Shalini   90000
108             Ayesha   60000
110          Shamiksha   45000

In [ ]:
df1.loc[105,'Salary']                             # df1.loc[105]['Salary']

90000

In [ ]:
df1.loc[[105,108,110], 'Salary']

Employee_ID
105    90000
108    60000
110    45000
Name: Salary, dtype: int64

In [ ]:
df1.loc[[105,108,110, 101], ['Name','Salary']]

                  Name  Salary
Employee_ID
105            Shalini   90000
108             Ayesha   60000
110          Shamiksha   45000
101            Utkarsh   95000

In [ ]:
df1.loc[101:106]

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5  Female   90000
106             Pratik   6    Male   80000

In [ ]:
df1.loc[101:106, ['Name','Salary']]

                  Name  Salary
Employee_ID
101            Utkarsh   95000
102             Kartik   85000
103          Aishwarya   75000
104              Anand   65000
105            Shalini   90000
106             Pratik   80000

In [ ]:
# To remember
print(df1['Name'])
print(df1.loc[101])
print(df1.loc[101,'Salary'])

Employee_ID
101      Utkarsh
102       Kartik
103    Aishwarya
104        Anand
105      Shalini
106       Pratik
107     Monalika
108       Ayesha
109        Anant
110    Shamiksha
111     Prashant
112       Mohini
Name: Name, dtype: object
Name      Utkarsh
ID              1
Gender       Male
Salary      95000
Name: 101, dtype: object
95000

## Adding and Deleting Rows and Columns

In [ ]:
df1

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5  Female   90000
106             Pratik   6    Male   80000
107           Monalika   7  Female   70000
108             Ayesha   8  Female   60000
109              Anant   9    Male  100000
110          Shamiksha  10  Female   45000
111           Prashant  11    Male   55000
112             Mohini  12  Female   65000

In [ ]:
df1.loc[113] = ['Priti', 13, 'Female', 71000]
df1

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5  Female   90000
106             Pratik   6    Male   80000
107           Monalika   7  Female   70000
108             Ayesha   8  Female   60000
109              Anant   9    Male  100000
110          Shamiksha  10  Female   45000
111           Prashant  11    Male   55000
112             Mohini  12  Female   65000
113              Priti  13  Female   71000

In [ ]:
df1['Age'] = np.random.randint(25,50,13)
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   38
102             Kartik   2    Male   85000   34
103          Aishwarya   3  Female   75000   34
104              Anand   4    Male   65000   42
105            Shalini   5  Female   90000   40
106             Pratik   6    Male   80000   45
107           Monalika   7  Female   70000   25
108             Ayesha   8  Female   60000   27
109              Anant   9    Male  100000   33
110          Shamiksha  10  Female   45000   40
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   37
113              Priti  13  Female   71000   43

In [ ]:
# df1.drop(113)
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   38
102             Kartik   2    Male   85000   34
103          Aishwarya   3  Female   75000   34
104              Anand   4    Male   65000   42
105            Shalini   5  Female   90000   40
106             Pratik   6    Male   80000   45
107           Monalika   7  Female   70000   25
108             Ayesha   8  Female   60000   27
109              Anant   9    Male  100000   33
110          Shamiksha  10  Female   45000   40
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   37
113              Priti  13  Female   71000   43

In [ ]:
df1.drop(113, inplace = True, axis = 0)   # Dropping a row, axis = 0
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   38
102             Kartik   2    Male   85000   34
103          Aishwarya   3  Female   75000   34
104              Anand   4    Male   65000   42
105            Shalini   5  Female   90000   40
106             Pratik   6    Male   80000   45
107           Monalika   7  Female   70000   25
108             Ayesha   8  Female   60000   27
109              Anant   9    Male  100000   33
110          Shamiksha  10  Female   45000   40
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   37

In [ ]:
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   38
102             Kartik   2    Male   85000   34
103          Aishwarya   3  Female   75000   34
104              Anand   4    Male   65000   42
105            Shalini   5  Female   90000   40
106             Pratik   6    Male   80000   45
107           Monalika   7  Female   70000   25
108             Ayesha   8  Female   60000   27
109              Anant   9    Male  100000   33
110          Shamiksha  10  Female   45000   40
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   37

In [ ]:
df1['City'] = 'Jaipur'
df1

                  Name  ID  Gender  Salary  Age    City
Employee_ID
101            Utkarsh   1    Male   95000   38  Jaipur
102             Kartik   2    Male   85000   34  Jaipur
103          Aishwarya   3  Female   75000   34  Jaipur
104              Anand   4    Male   65000   42  Jaipur
105            Shalini   5  Female   90000   40  Jaipur
106             Pratik   6    Male   80000   45  Jaipur
107           Monalika   7  Female   70000   25  Jaipur
108             Ayesha   8  Female   60000   27  Jaipur
109              Anant   9    Male  100000   33  Jaipur
110          Shamiksha  10  Female   45000   40  Jaipur
111           Prashant  11    Male   55000   39  Jaipur
112             Mohini  12  Female   65000   37  Jaipur

In [ ]:
df1.drop('City', inplace = True, axis = 1)   # Dropping a column, axis = 1
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   38
102             Kartik   2    Male   85000   34
103          Aishwarya   3  Female   75000   34
104              Anand   4    Male   65000   42
105            Shalini   5  Female   90000   40
106             Pratik   6    Male   80000   45
107           Monalika   7  Female   70000   25
108             Ayesha   8  Female   60000   27
109              Anant   9    Male  100000   33
110          Shamiksha  10  Female   45000   40
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   37

In [ ]:
df1.loc[101, 'Salary'] = 200000
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   38
102             Kartik   2    Male   85000   34
103          Aishwarya   3  Female   75000   34
104              Anand   4    Male   65000   42
105            Shalini   5  Female   90000   40
106             Pratik   6    Male   80000   45
107           Monalika   7  Female   70000   25
108             Ayesha   8  Female   60000   27
109              Anant   9    Male  100000   33
110          Shamiksha  10  Female   45000   40
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   37

In [ ]:
df1.loc[[102,103], 'Salary'] = [80000, 90000]
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   38
102             Kartik   2    Male   80000   34
103          Aishwarya   3  Female   90000   34
104              Anand   4    Male   65000   42
105            Shalini   5  Female   90000   40
106             Pratik   6    Male   80000   45
107           Monalika   7  Female   70000   25
108             Ayesha   8  Female   60000   27
109              Anant   9    Male  100000   33
110          Shamiksha  10  Female   45000   40
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   37

## Querying Based on Condition

In [ ]:
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   38
102             Kartik   2    Male   80000   34
103          Aishwarya   3  Female   90000   34
104              Anand   4    Male   65000   42
105            Shalini   5  Female   90000   40
106             Pratik   6    Male   80000   45
107           Monalika   7  Female   70000   25
108             Ayesha   8  Female   60000   27
109              Anant   9    Male  100000   33
110          Shamiksha  10  Female   45000   40
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   37

In [ ]:
df1.Age > 40

Employee_ID
101    False
102    False
103    False
104     True
105    False
106     True
107    False
108    False
109    False
110    False
111    False
112    False
Name: Age, dtype: bool

In [ ]:
df1[df1.Age > 40]

               Name  ID Gender  Salary  Age
Employee_ID
104           Anand   4   Male   65000   42
106          Pratik   6   Male   80000   45

In [ ]:
df1[df1.Age > 40][['Name', 'Age', 'Salary']]

               Name  Age  Salary
Employee_ID
104           Anand   42   65000
106          Pratik   45   80000

In [ ]:
df1[df1['Salary'] < 70000]

                  Name  ID  Gender  Salary  Age
Employee_ID
104              Anand   4    Male   65000   42
108             Ayesha   8  Female   60000   27
110          Shamiksha  10  Female   45000   40
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   37

In [ ]:
df1[df1.Salary < 70000][['Name', 'Salary']]

                  Name  Salary
Employee_ID
104              Anand   65000
108             Ayesha   60000
110          Shamiksha   45000
111           Prashant   55000
112             Mohini   65000

In [ ]:
df1[df1.Gender == 'Male']

                 Name  ID Gender  Salary  Age
Employee_ID
101           Utkarsh   1   Male  200000   38
102            Kartik   2   Male   80000   34
104             Anand   4   Male   65000   42
106            Pratik   6   Male   80000   45
109             Anant   9   Male  100000   33
111          Prashant  11   Male   55000   39

In [ ]:
df1[df1.Gender == 'Male'][df1.Salary >= 80000]

                Name  ID Gender  Salary  Age
Employee_ID
101          Utkarsh   1   Male  200000   38
102           Kartik   2   Male   80000   34
106           Pratik   6   Male   80000   45
109            Anant   9   Male  100000   33

In [ ]:
df1['Salary'][105] = 150000

In [ ]:
df1[df1.Gender == 'Female'][df1.Salary < 100000]

                  Name  ID  Gender  Salary  Age
Employee_ID
103          Aishwarya   3  Female   90000   34
107           Monalika   7  Female   70000   25
108             Ayesha   8  Female   60000   27
110          Shamiksha  10  Female   45000   40
112             Mohini  12  Female   65000   37

In [ ]:
df1[(df1.Gender == 'Female') & (df1.Salary < 100000)]

                  Name  ID  Gender  Salary  Age
Employee_ID
103          Aishwarya   3  Female   90000   34
107           Monalika   7  Female   70000   25
108             Ayesha   8  Female   60000   27
110          Shamiksha  10  Female   45000   40
112             Mohini  12  Female   65000   37

In [ ]:
df1[(df1.Age < 30) | (df1.Age > 45)]

                 Name  ID  Gender  Salary  Age
Employee_ID
107          Monalika   7  Female   70000   25
108            Ayesha   8  Female   60000   27

In [ ]:
df1[df1.Gender == 'Male'][df1.Salary > 80000][df1.Salary < 150000]

              Name  ID Gender  Salary  Age
Employee_ID
109          Anant   9   Male  100000   33

In [ ]:
# Extract name, gender and salary of all male employees having salary between 80000 to 120000
df1[df1.Gender == 'Male'][df1.Salary >= 80000][df1.Salary <= 120000][['Name', 'Gender', 'Salary']]

               Name Gender  Salary
Employee_ID
102          Kartik   Male   80000
106          Pratik   Male   80000
109           Anant   Male  100000

In [ ]:
df1[df1.Salary > 70000]

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   38
102             Kartik   2    Male   80000   34
103          Aishwarya   3  Female   90000   34
105            Shalini   5  Female  150000   40
106             Pratik   6    Male   80000   45
109              Anant   9    Male  100000   33

In [ ]:
df1.query('Salary > 70000')

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   38
102             Kartik   2    Male   80000   34
103          Aishwarya   3  Female   90000   34
105            Shalini   5  Female  150000   40
106             Pratik   6    Male   80000   45
109              Anant   9    Male  100000   33

In [ ]:
df1.query('Gender == "Male"')

                 Name  ID Gender  Salary  Age
Employee_ID
101           Utkarsh   1   Male  200000   38
102            Kartik   2   Male   80000   34
104             Anand   4   Male   65000   42
106            Pratik   6   Male   80000   45
109             Anant   9   Male  100000   33
111          Prashant  11   Male   55000   39

In [ ]:
df1.query('Salary > 70000 and Age > 40')

               Name  ID Gender  Salary  Age
Employee_ID
106          Pratik   6   Male   80000   45

In [ ]:
df1.query('Salary >= 70000 and Salary <= 90000')

                  Name  ID  Gender  Salary  Age
Employee_ID
102             Kartik   2    Male   80000   34
103          Aishwarya   3  Female   90000   34
106             Pratik   6    Male   80000   45
107           Monalika   7  Female   70000   25

In [ ]:
# Extract name, gender and salary of all male employees having salary between 80000 to 120000
df1.query("Gender == 'Male' and Salary >= 80000 and Salary <= 120000")[['Name', 'Gender', 'Salary']]

               Name Gender  Salary
Employee_ID
102          Kartik   Male   80000
106          Pratik   Male   80000
109           Anant   Male  100000

In [ ]:
# Extract all employees having salary more than the average salary
df1[df1.Salary > df1.Salary.mean()]

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   38
103          Aishwarya   3  Female   90000   34
105            Shalini   5  Female  150000   40
109              Anant   9    Male  100000   33

In [ ]:
df1.Salary.mean()

88333.33333333333

In [ ]:
"{}".format(df1.Salary.mean())

'88333.33333333333'

In [ ]:
df1.query('Salary > {}'.format(df1.Salary.mean()))

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   38
103          Aishwarya   3  Female   90000   34
105            Shalini   5  Female  150000   40
109              Anant   9    Male  100000   33

In [ ]:
df1.query('Salary > '+ str(df1.Salary.mean()))

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   38
103          Aishwarya   3  Female   90000   34
105            Shalini   5  Female  150000   40
109              Anant   9    Male  100000   33